language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

before_install:
  - docker --version

script:
  - docker build --pull -f ci/Dockerfile.android -t cordova-template-vue .
